config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/robot.rb
class Robot

  def self.track_tweets(hashtag, since = nil, _until = nil)
    query = {
      f: 'tweets',
      q: "#{hashtag} since:#{since} until:#{_until}",
    }
    url = URI.encode('https://twitter.com/search')
    query_string = URI.encode_www_form(query)
    uri = "#{url}?#{query_string}"
    puts uri

    ChromeClient.new_session
    ChromeClient.visit(uri)
    html = ChromeClient.html
    doc = Nokogiri::HTML(html)

    tweets = doc.search('//*[@id="stream-items-id"]/li').css('.stream-item')
    save_tweets(tweets, more: true)
  end

  def self.save_tweets(tweets, more: false)
    @count ||= 0
    @page ||= 1
    @coder ||= HTMLEntities.new

    tweets.each do |tweet|
      author = Author.find_or_create_by({
           name: tweet.css('.fullname').text.gsub(/(Verified account)/,'').strip,
           alias: "@"+tweet.css('.username b').text.strip
      })

      Tweet.find_or_create_by({
          author: author,
          tw_tweet_id: tweet.attr('data-item-id')
        }) do |tw|
        tw.text = @coder.decode(Sanitize.fragment(tweet.css('.js-tweet-text-container')))
        tw.date = DateTime.parse(tweet.css('.time > a').attr('title'))
        tw.save
      end

      @count += 1
      @last = tweet.attr('data-item-id')
    end

    puts "#{Time.now.to_s} - Página #{@page}, #{@count} tweets processados"

    if more
      while not more_tweets.empty?
        tweets = more_tweets
        @page += 1
        save_tweets(tweets)
      end
    end
  end

  def self.more_tweets
    begin
      ChromeClient.scroll_bottom
      sleep 8
      html = ChromeClient.html
      doc = Nokogiri::HTML(html)
      tweets = doc.search('//*[@id="stream-items-id"]/li').css('.stream-item')

      #notnothing more was loaded
      return [] if tweets.last.attr('data-item-id') == @last

      #remove tweets already processed
      return tweets.drop(@count)
    rescue Exception => e
      return []
    end
  end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :author

  scope :like, -> (q)  { where('text LIKE ?', "%#{q}%") }
  scope :since, -> (date)  { where('date >= ?', Time.parse(date).at_beginning_of_day )}
  scope :until, -> (date)  { where('date <= ?', Time.parse(date).at_end_of_day)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :alias, :tw_user_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.eager_load(:author)
    @tweets = @tweets.since(params[:since]) if params[:since]
    @tweets = @tweets.until(params[:until]) if params[:until]
    @tweets = @tweets.like(params[:q]) if params[:q]
    @tweets
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:author_id, :text, :date, :tw_tweet_id, :language)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :alias %>
    <%= f.text_field :alias %>
  </div>

  <div class="field">
    <%= f.label :tw_user_id %>
    <%= f.text_field :tw_user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Alias</th>
      <th>Tw user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.alias %></td>
        <td><%= author.tw_user_id %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @author.alias %>
</p>

<p>
  <strong>Tw user:</strong>
  <%= @author.tw_user_id %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_id %>
    <%= f.text_field :author_id %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :tw_tweet_id %>
    <%= f.text_field :tw_tweet_id %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Text</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><b><%= tweet.author.name %></b> <br> <%= tweet.author.alias %></td>
        <td><%= tweet.text %></td>
        <td><%= tweet.date %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @tweet.author %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>Date:</strong>
  <%= @tweet.date %>
</p>

<p>
  <strong>Tw tweet:</strong>
  <%= @tweet.tw_tweet_id %>
</p>

<p>
  <strong>Language:</strong>
  <%= @tweet.language %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>